// Generated by CoffeeScript 1.6.2
(function() {
  var bitly, bitlyClient;

  bitlyClient = require('./index');

  bitly = new bitlyClient(process.env.user, process.env.pwd, function(error) {
    if (!error) {
      return bitly.get('highvalue', {
        limit: 3
      }, function(error, result) {
        return console.log(!error ? result : error);
      });
    } else {
      return console.log(error);
    }
  });

}).call(this);
