// Generated by CoffeeScript 1.6.2
(function() {
  var bitly, bitlyClient;

  bitlyClient = require('./index');

  bitly = new bitlyClient(process.env.user, process.env.password, function(error) {
    if (!error) {
      return bitly.get('highvalue', {
        'limit': 2
      }, function(error, result) {
        return console.log(!error ? result : error);
      });
    }
  });

}).call(this);
