// Generated by CoffeeScript 1.6.2
(function() {
  var bitly, bitlyClient;

  bitlyClient = require('bitly2');

  bitly = new bitlyClient(process.env.bitly_user, process.env.bitly_password, function(error) {
    if (!error) {
      return bitly.get('highvalue', {
        'limit': 2
      }, function(error, result) {
        if (!error) {
          return console.log(result);
        }
      });
    }
  });

}).call(this);
